version: '3.8'

services:
  db:
    image: postgres:13.10
    container_name: app_development_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development_db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: ['sh', '-c', 'rails db:create && rails db:migrate && rails db:seed && rails server -b 0.0.0.0']

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
    command: ['npm','start']
