default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: user
  password: password


development:
  <<: *default
  database: app_development_db